### ISSUE TITLE
Solver Cannot Find an Optimal Solution

### ISSUE THREAD

**Issue by ChristoMI** [V2A2/StarV_temp#17]
**Class**: ImageStar
**Method**: sample
**Line**: 376
**Error**: _Cannot find an optimal solution, exitflag = 4_
**Tagged developers**: @csw94056 

**Error file**: https://github.com/transafeailab/StarV/blob/dev/engine/set/imagestar/imagestar.py
**Test file**: https://github.com/transafeailab/StarV/blob/dev/tests/set/image_star/test_ImageStar_sample.py

**Full Stack Trace**:
Exception type : Exception 
Exception message : error: Cannot find an optimal solution, exitflag = 4
Stack trace : File : tests/set/image_star/test_ImageStar_sample.py ,
 Line : 37,
 Func.Name : test_sampling,
 Message : images = test_star.sample(test_N)
File : /home/crescendo/Workspace/StarV/engine/set/imagestar/imagestar.py ,
 Line : 376,
 Func.Name : sample,
 Message : pred_samples = S.sample(N)
File : /home/crescendo/Workspace/StarV/engine/set/star/star.py ,
 Line : 263,
 Func.Name : sample,
 Message : B = self.getBox()
File : /home/crescendo/Workspace/StarV/engine/set/star/star.py ,
 Line : 480,
 Func.Name : getBox,
 Message : raise Exception('error: Cannot find an optimal solution, exitflag = %d' % (ub_.status))

**Comment by csw94056** [comment]
The issue is not a gurobi problem. I have no idea how you constructed ImageStar initially, but it seems like the loaded ImageStar has V, predicate_lb, and predicate_ub. However, C is a 2D numpy array with all zeros, and d is a 1D numpy array in form of [0]. Before sampling, you modified V such that a constructed star has a center vector (=a zero vector) and basis matrix (=eye matrix). This means you have constructed an infeasible star set. Therefore,  gurobi will return an exitflag = 4, which means "Model was proven to be either infeasible or unbounded." I fixed the issue but a new issue is raised. 

Exception type : TypeError 
Exception message : list.append() takes exactly one argument (2 given)
Stack trace : File : c:\Users\schoi\Documents\Github\StarV\StarV_dev\StarV\tests\set\image_star\test_ImageStar_sample.py ,
 Line : 36,
 Func.Name : test_sampling,
 Message : images = test_star.sample(test_N)
File : C:\Users\schoi\Documents\Github\StarV\StarV_dev\StarV\engine/set/imagestar\imagestar.py ,
 Line : 381,
 Func.Name : sample,
 Message : images.append(images, np.array(self.evaluate(pred_samples[:, i])))
